wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 5
      - 9
      2:
      - 1
      - 5
      - 9
      3:
      - 2
      4: 3.8.5
      5: 0.10.21
      8:
      - 5
batch_size:
  desc: null
  value: 512
learning_rate:
  desc: null
  value: 0.001
momentum:
  desc: null
  value: 0.9
n_epochs:
  desc: null
  value: 10
num_classes:
  desc: null
  value: 10
num_kernels_layer1:
  desc: null
  value: 6
num_kernels_layer2:
  desc: null
  value: 16
num_kernels_layer3:
  desc: null
  value: 120
num_nodes_fc_layer:
  desc: null
  value: 84
weight_decay:
  desc: null
  value: 0.0001
