wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      4: 3.6.9
      5: 0.10.18
batch_size:
  desc: null
  value: 128
criterion:
  desc: null
  value: mse
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.9
optimizer:
  desc: null
  value: sgd
weight_decay:
  desc: null
  value: 0.005
